### ISSUE TITLE
Refresh button stopped working - VS Pro 2019 16.3.0

### ISSUE THREAD

**Issue by fwd079** [luminous-software/developer-news#7]
### Installed product versions
- Visual Studio: Visual Studio 2019 Professional v 16.3.0
- This extension: Developer news

### Description
Stopped working in 16.3.0

### Steps to recreate
1. Update Visual Studio to 2019 v 16.3.0
2. Restart VS/PC etc.
3. Go to developer news.
4. Click on Refresh button.
5. Older news are showing.

### Current behavior
Older news showing, Refresh button doesn't work.

### Expected behavior
Refresh button to refresh the news.

Regards.

**Comment by fwd079** [comment]
**Screenshot added.**
_
![image](https://user-images.githubusercontent.com/7912632/65493093-0fa83800-deaa-11e9-9406-f1b39dc07c89.png)

**Comment by yannduran** [comment]
I know this can be confusing, especially when nobody's explained how it works. I had to work it out for myself. Basically there are two **separate** feeds:

- Developer News
- Visual Studio Blog

I don't know how many items used to be in the original _Developer News_ feed in VS 2017, because I used to use a start page extension that provided a custom start page which didn't have a _Developer News_ section in it. 

I display the exact **same** feed in my _Developer News_ extension that was in VS 2017's _Developer News_, only for some reason that I can't remember, I only display the last **seven** items (I think it was because that was how many items fitted on a page without a scrollbar). 

When they killed the start page in VS 2019, and switched to displaying a _Developer News_ section in the VS installer, they displayed a much smaller number of items, and now they only show **three** items in it, relying instead on the _View More News_ link instead. I don't know where the original link used to go to, but now it goes to the VS Blog's page.

The original feed, or a clone of it, is still being maintained by Microsoft, but it only contains a maximum of **ten** items. When they add a new item, it seems that they delete the oldest one at the same time. When I wrote _Start Page+_ I decided to display the full **ten** items.

My _View More News_ link also opens the Visual Studio Blog page, which is what the link in the installer displays. 

The items in the two feeds are very similar, but it appears that they may be maintained by two different teams, because they don't always have exactly the same items. I've seen items that were in the _Developer News_ feed that weren't in the _VS Blog_, and I've seen items that were in the blog that weren't in _Developer News_.

So the _Refresh_ button hasn't actually stopped working, it seems that you've compared the two feeds at a time where they don't match. The refresh was actually so fast that I could never tell if it had refreshed or not, so I now clear the list first, so there's a visual cue that the refresh has in fact taken place.

I hope all that helps.

**Comment by fwd079** [comment]
Cool, if that is the way it works, then perhaps the **View more news** should take you to the feed inside the box, not the other feed?

Either way, now they are synced, will go out of sync again I am sure, because Microsoft. 

Closing this as this isn't a bug (at least not in your part).

Regards.
